Fix gcc_stm32f3.cmake
Add `-fno-builtin` and other flags that were only set for C++.

Specifically, adding `-fno-builtin` fixes some undefined reference to some `math.h` functiosn such as `ceil`, `floor` and `round`, when the link time optimizer is activated (with `-flto` flag).